### ISSUE TITLE
TypeError when executing scriptwriter in the console

### ISSUE THREAD

**Issue by shtlrs** [AutoSponge/scriptwriter#125]
Hi,

I've just installed scriptwriter and followed the steps in the README file.
I'm on windows 10 and I have  the following packages installed:
- node v 1.14.16
- playwright 1.12.2

The issue is, when I execute  `scriptwriter` in console, I get the following:
```JSON
{
  headless: true,
  browser: 'chromium',
  js: true,
  csp: true,
  aom: false,
  user: ''
}
``` 
>   TypeError: Cannot read property 'commands' of undefined

  - scriptwriter.js:163 Scriptwriter.init
    [npm]/[scriptwriter]/lib/scriptwriter.js:163:25

  - cli.js:94 Object.<anonymous>
    [npm]/[scriptwriter]/bin/cli.js:94:14

  - loader.js:1063 Module._compile
    internal/modules/cjs/loader.js:1063:30

  - loader.js:1092 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1092:10

  - loader.js:928 Module.load
    internal/modules/cjs/loader.js:928:32

  - loader.js:769 Function.Module._load
    internal/modules/cjs/loader.js:769:14

  - run_main.js:72 Function.executeUserEntryPoint [as runMain]
    internal/modules/run_main.js:72:12

  - run_main_module.js:17
    internal/main/run_main_module.js:17:47

TypeError: Cannot read property 'commands' of undefined
    at Scriptwriter.init (C:\Users\Amrou Bellalouna\AppData\Roaming\npm\node_modules\scriptwriter\lib\scriptwriter.js:163:25)
    at Object.<anonymous> (C:\Users\Amrou Bellalouna\AppData\Roaming\npm\node_modules\scriptwriter\bin\cli.js:94:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by shtlrs** [comment]
Seems this will never get any love, closing it.
